### ISSUE TITLE
Homework Task Issue

### ISSUE THREAD

**Issue by CCajamarca3** [CCajamarca3/SSW345#1]
## Homework Tasks

This issue is used to track my homework tasks.

### To-Do List

- [ ] Upload GitHub profile picture
- [ ] Set up Project Teams with Philip and Ahmad
- [ ] Upload my resume to LinkedIn

### Task Details

- [ ] I need to get my resume updated.
- [ ] Find a good picture to make a profile pic.
